#  ____  __  __ ______        ___       _
# / ___||  \/  | __ ) \      / (_)_ __ | |_ ___ _ __
# \___ \| |\/| |  _ \\ \ /\ / /| | '_ \| __/ _ \ '__|
#  ___) | |  | | |_) |\ V  V / | | | | | ||  __/ |
# |____/|_|  |_|____/  \_/\_/  |_|_| |_|\__\___|_|
#
# Samuel.M.B.Winter@protonmail.com
# https://github.com/SamuelMBWinter
# 
# Here is my starship prompt configuration 
# This currently is only set up with the modules I use the most often.


# Don't print a new line at the start of the prompt
add_newline = false

# Prompt format
format = """
[┌────](bold blue)$directory$git_branch$git_commit$git_state$git_status$python
[└── ](bold blue)$character"""

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"
vicmd_symbol = "[❮](bold green)"

# Changing the displayed path
[directory]
truncation_length = 1

# Language modules
[python]
format = '[${symbol}${version} ]($style)'
symbol = " "
style = "yellow"

# Git modules

[git_branch]
format = '[${symbol}${branch} ]($style)'
symbol = " "
style = "purple"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

